[void] [System.Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms") 
[System.Windows.forms.SendKeys]::SendWait("D:")
[System.Windows.forms.SendKeys]::SendWait("{ENTER}")
[System.Windows.forms.SendKeys]::SendWait("Programming")
[System.Windows.forms.SendKeys]::SendWait("{ENTER}")
[System.Windows.forms.SendKeys]::SendWait("Java")
[System.Windows.forms.SendKeys]::SendWait("{ENTER}")
[System.Windows.forms.SendKeys]::SendWait("Programs")
[System.Windows.forms.SendKeys]::SendWait("{ENTER}")
[System.Windows.forms.SendKeys]::SendWait("Testing java")
[System.Windows.forms.SendKeys]::SendWait("{ENTER}")
[System.Windows.forms.SendKeys]::SendWait("Testing")
[System.Windows.forms.SendKeys]::SendWait("{ENTER}")
[System.Windows.forms.SendKeys]::SendWait("Main.java")
[System.Windows.forms.SendKeys]::SendWait("{ENTER}")